name: Continuous integration (CI)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, feature/** ]

jobs:
  test:
    env:
      TURBO_TELEMETRY_DISABLED: 1
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 18.20.4, 20.18.0 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4.1.7

      - name: Node.js setup ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: ${{ matrix.node-version }}

      - name: Dependencies installation
        run: npm ci

      - name: Test
        run: npm test
