name: Security

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '25 16 * * 4'

jobs:
  security:
    name: Snyk
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4.1.7

      - continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        name: Snyk vulnerabilities scan
        uses: snyk/actions/node@0.4.0
        with:
          args: --sarif-file-output=snyk.sarif

      - name: SARIF upload to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3.26.8
        with:
          sarif_file: snyk.sarif
